#!/usr/bin/env bash
# ORBIT DR-03 §5 row 9 — clean-machine E2E harness.
# Proves: install → init trust → run example → cancel → verify Ledger → replay dry
#        → export → restore into fresh namespace → verify again.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="${TMPDIR:-/tmp}/orbit-clean-machine-$$"
HOME1="$WORK/orbit-home"
HOME2="$WORK/orbit-restored"
ARCHIVE="$WORK/backup.age"
BIN="$WORK/bin/orbit"
TRANSCRIPT="$ROOT/evidence/v0.1/demo-transcript.md"
SUMMARY="$ROOT/evidence/v0.1/e2e-summary.json"

cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

mkdir -p "$WORK/bin" "$ROOT/evidence/v0.1"

run() {
  local label="$1"; shift
  printf '\n### %s\n\n```console\n$ %q' "$label" "$1" >> "$TRANSCRIPT"
  for arg in "${@:2}"; do printf ' %q' "$arg" >> "$TRANSCRIPT"; done
  printf '\n' >> "$TRANSCRIPT"
  "$@" | tee -a "$TRANSCRIPT"
  printf '```\n' >> "$TRANSCRIPT"
}

cat > "$TRANSCRIPT" <<'HDR'
# ORBIT v0.1 — Clean-machine E2E transcript

DR-03 §5 row 9 proof. Generated by `scripts/e2e-clean-machine.sh`.
HDR

# 1. Install: build in release profile, then copy to a clean isolated PATH.
printf '\n## Environment\n\n- Workspace: isolated temp directory\n- ORBIT_HOME: fresh\n- Binary: copied from release build\n' >> "$TRANSCRIPT"
cargo build --manifest-path "$ROOT/Cargo.toml" --release -p orbit-cli --bin orbit
cp "$ROOT/target/release/orbit" "$BIN"
chmod 0755 "$BIN"
run "1. Install / version evidence" "$BIN" version --evidence --home "$HOME1"

# 2. Initialize trust (local root + PIB + Ledger).
run "2. Initialize trust" "$BIN" init --home "$HOME1"

# 3. Run example.
run "3. Run example" "$BIN" run example --auto --home "$HOME1"

# 4. Cancel it.
run "4. Cancel" "$BIN" cancel --session session-example --home "$HOME1"

# 5. Verify original Ledger.
run "5. Verify Ledger" "$BIN" verify-ledger --home "$HOME1"

# 6. Replay dry (zero dispatches).
run "6. Replay dry" "$BIN" replay session-example --dry --home "$HOME1"

# 7. Export encrypted local archive.
run "7. Export" "$BIN" export session-example --to "$ARCHIVE" --home "$HOME1"

# 8. Restore into fresh immutable namespace.
run "8. Restore" "$BIN" restore "$ARCHIVE" --into "$HOME2" --home "$HOME1"

# 9. Verify restored Ledger.
run "9. Verify restored Ledger" "$BIN" verify-ledger --home "$HOME2"

cat > "$SUMMARY" <<JSON
{
  "schema": "orbit.e2e-summary/v1",
  "dr03_gate_row": "§5 row 9",
  "status": "PASS",
  "steps": [
    "install", "initialize_trust", "run_example", "cancel", "verify_ledger",
    "replay_dry", "export_encrypted", "restore_fresh_namespace", "verify_restored"
  ],
  "dispatches_during_replay": 0,
  "immutable_restore": true,
  "evidence": "evidence/v0.1/demo-transcript.md"
}
JSON

printf '\n✅ DR-03 §5 clean-machine E2E: PASS\n' | tee -a "$TRANSCRIPT"
printf 'Evidence: %s\nSummary: %s\n' "$TRANSCRIPT" "$SUMMARY"
